### ISSUE TITLE
reporte

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-vaii#1]
[Conexión de Datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-vaii/files/6770836/Conexion.de.Datos.pdf)

**Comment by IsaHuerta23** [comment]
Cumple con todos los puntos de la rúbrica. 
Calificación: 20.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
